orig_galaxy = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""

expanded_galaxy = """....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#......."""


def convert_mul_line_to_2D(data):
    maze = []
    for line in data.split("\n"):
        maze.append(list(line))
    return maze

def test_expand_galaxy():
    new_galaxy

def test_get_sum_of_shortest_paths():
    sum_of_lngths = 0
    assert sum_of_lngths == 374